name: Test Main Branch
on:
  pull_request:
    branches:
      - 'main'

env:
  IS_CI: true
  GRADLE_OPTS: "-Dfile.encoding=UTF-8"

jobs:
  build-test:
    name: Build and test main
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
        java: [ 11, 17, 21 ]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'
          java-version: ${{ matrix.java }}
          cache: 'gradle'

      - name: Run All Tests
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: 8.5
          arguments: |
            assemble
            build
            allTests
            --info 
            --warning-mode all
